#!/bin/bash
# GitHub Pages 配置检查和修复脚本

echo "======================================"
echo "GitHub Pages 配置诊断"
echo "======================================"
echo ""

echo "📋 步骤 1：检查仓库可见性"
echo "--------------------------------------"
echo "访问: https://github.com/yxw839841231/btc-momentum-service/settings"
echo ""
echo "确认："
echo "  • Repository visibility 应该是 Public（公开）"
echo "  • 如果是 Private，GitHub Pages 无法免费使用"
echo ""
echo "如果是 Private，需要改为 Public："
echo "  1. 滚动到页面底部的 'Danger Zone'"
echo "  2. 点击 'Change repository visibility'"
echo "  3. 选择 'Public'"
echo ""

read -p "按回车继续..."

echo ""
echo "📋 步骤 2：配置 GitHub Pages"
echo "--------------------------------------"
echo "访问: https://github.com/yxw839841231/btc-momentum-service/settings/pages"
echo ""
echo "正确的配置："
echo "  Source: 选择 'Deploy from a branch'"
echo "  Branch: gh-pages"
echo "  Folder: / (root)"
echo ""
echo "或者："
echo "  Source: 选择 'GitHub Actions'"
echo "  （推荐，因为我们使用 Actions 部署）"
echo ""

echo "📋 步骤 3：检查 gh-pages 分支"
echo "--------------------------------------"
echo "访问: https://github.com/yxw839841231/btc-momentum-service/branches"
echo ""
echo "查找 'gh-pages' 分支："
echo "  • 如果存在：点击查看是否有 index.html 和 reports/ 目录"
echo "  • 如果不存在：需要手动触发 Actions 生成"
echo ""

echo "📋 步骤 4：手动触发 Actions"
echo "--------------------------------------"
echo "1. 访问: https://github.com/yxw839841231/btc-momentum-service/actions"
echo "2. 点击 'BTC Momentum Analysis' workflow"
echo "3. 点击 'Run workflow' 按钮"
echo "4. 选择分支 'main'"
echo "5. 点击 'Run workflow' 确认"
echo "6. 等待 1-2 分钟完成"
echo ""

read -p "按回车继续..."

echo ""
echo "📋 步骤 5：等待 GitHub Pages 部署"
echo "--------------------------------------"
echo "GitHub Pages 部署需要时间："
echo "  • 通常需要 1-3 分钟"
echo "  • 有时可能需要更久（首次部署）"
echo ""
echo "检查部署状态："
echo "  访问: https://github.com/yxw839841231/btc-momentum-service/settings/pages"
echo "  查看顶部的提示信息"
echo ""

echo "📋 步骤 6：检查常见问题"
echo "--------------------------------------"
echo ""
echo "问题 A: 404 Not Found"
echo "  原因 1: 仓库是 Private 的"
echo "  解决: 改为 Public"
echo ""
echo "  原因 2: gh-pages 分支不存在"
echo "  解决: 触发 Actions 生成"
echo ""
echo "  原因 3: index.html 不在根目录"
echo "  解决: 检查 gh-pages 分支的文件结构"
echo ""
echo "问题 B: 403 Forbidden"
echo "  原因: 仓库是 Private 的"
echo "  解决: 改为 Public"
echo ""

echo "======================================"
echo "完成！"
echo "======================================"
echo ""
echo "✅ 完成配置后，访问："
echo "   https://yxw839841231.github.io/btc-momentum-service/"
echo ""
