#!/bin/bash
# GitHub Pages 诊断脚本

echo "======================================"
echo "GitHub Pages 诊断工具"
echo "======================================"
echo ""

echo "1. 检查本地报告文件"
echo "--------------------------------------"
ls -lh reports/*.html 2>/dev/null || echo "❌ 本地没有 HTML 报告"
echo ""

echo "2. 检查 GitHub Pages 配置"
echo "--------------------------------------"
echo "请确认以下设置："
echo ""
echo "访问: https://github.com/yxw839841231/btc-momentum-service/settings/pages"
echo ""
echo "正确的配置应该是："
echo "  Source: GitHub Actions"
echo "  Branch: (不适用，因为使用 GitHub Actions)"
echo ""
echo "如果 Source 不是 'GitHub Actions'，请："
echo "  1. 点击 Source 下拉菜单"
echo "  2. 选择 'GitHub Actions'"
echo "  3. 点击 Save"
echo ""

echo "3. 检查 gh-pages 分支"
echo "--------------------------------------"
echo "GitHub Pages 内容通常在 gh-pages 分支"
echo ""
echo "查看 gh-pages 分支："
echo "  https://github.com/yxw839841231/btc-momentum-service/tree/gh-pages"
echo ""

echo "4. 手动部署测试"
echo "--------------------------------------"
echo "如果 GitHub Pages 没有自动部署，可以手动触发："
echo "  1. 访问: https://github.com/yxw839841231/btc-momentum-service/actions"
echo "  2. 点击 'BTC Momentum Analysis' workflow"
echo "  3. 点击 'Run workflow' 按钮"
echo "  4. 等待完成后查看 gh-pages 分支是否有新文件"
echo ""

echo "5. 报告 URL 格式"
echo "--------------------------------------"
echo "正确的报告 URL 格式："
echo "  https://yxw839841231.github.io/btc-momentum-service/reports/btc_analysis_20260127_115211.html"
echo ""
echo "注意："
echo "  - 文件名包含时间戳"
echo "  - 路径是 /reports/文件名.html"
echo "  - URL 是小写的"
echo ""

echo "6. 常见问题"
echo "--------------------------------------"
echo ""
echo "问题 A: 404 Not Found"
echo "原因: GitHub Pages 还没有部署或配置错误"
echo "解决: 确认 Settings → Pages → Source 是 'GitHub Actions'"
echo ""
echo "问题 B: 403 Forbidden"
echo "原因: 仓库是 Private 的"
echo "解决: 将仓库改为 Public（GitHub Pages 免费版要求）"
echo ""
echo "问题 C: 页面空白"
echo "原因: HTML 文件路径错误"
echo "解决: 检查 URL 路径是否正确"
echo ""

echo "======================================"
echo "诊断完成"
echo "======================================"
